version: '3'
services:
   mqttserver:
      image: eclipse-mosquitto
      container_name: mqttC
      ports:
         - 1883:1883
         - 9001:9001
      expose:
         - "1883"
      restart: always
   mongoserver:
      image: mongo
      container_name: mongoC
      #ports:
         #- 27017:27017
      expose:
         - "27017"            
      restart: always
   indexador:
      container_name: indexC
      build:
         context: ./indexador
      image: index
      depends_on:
         - mongoserver
         - mqttserver
   validador:
      container_name: validadorC
      build:
         context: ./validador
      image: valid
      depends_on:
         - mqttserver